### ISSUE TITLE
user is not signed in

### ISSUE THREAD

**Issue by juanxodj** [TasteBytes/POS#1]
I'm trying to start the project on my PC, but it shows me this error:

user is not signed in

ANY SOLUTION?

**Comment by danstans** [comment]
Hi @juanxodj, this was a project that I built for class and is no longer being maintained. Are your running the website or the downloadable application? I believe you can go to https://tastebytes.herokuapp.com/ to sign up for an account. Once you do that you may be able to sign into the POS application.

Of course, this project is not production ready. What are you trying to do with it?

**Comment by juanxodj** [comment]
I wanted to test the operation of Firebase in a POS system because I'm thinking of doing one with that tool.

**Comment by nbayt** [comment]
If I remember correctly, that error always shows up when you start the
server, but it still works as expected.

**Comment by danstans** [comment]
@nbayt  The user is not signed in is most likely just a console.log that didn't get removed :) Should not be an issue to performance or anything. Nice to hear from the group.

@juanxodj, firebase is a good option, however, I believe it can be a bit pricey compared to other services on scale and it may be better to host your own DB using SQL or mongo  on your own server. Firebase is great for MVP and applications that need real time database syncing. In my opinion, a POS system does not need real time integration the way firebase provides it. Let me know if you have any difficulties getting the application to work.
